FROM brew.registry.redhat.io/rh-osbs/openshift-ose-cli-rhel9:v4.19 AS oc
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:v1.23.2 AS builder

ENV PKG_PATH=/go/src/github.com/openshift-kni/cnf-features-deploy
ENV UTILS_PATH=$PKG_PATH/cnf-tests/pod-utils

WORKDIR $PKG_PATH
COPY . .

ENV GOFLAGS="-mod=vendor"
RUN make test-bin

WORKDIR ${UTILS_PATH}/stresser
RUN go build -mod=vendor -o /stresser

WORKDIR ${UTILS_PATH}/sctptester
RUN go build -mod=vendor -o /sctptest

WORKDIR ${UTILS_PATH}/hugepages-allocator
RUN go build -mod=vendor -o /hugepages-allocator

WORKDIR ${UTILS_PATH}
RUN go build -mod=vendor -o /oslat-runner oslat-runner/main.go && \
    go build -mod=vendor -o /cyclictest-runner cyclictest-runner/main.go && \
    go build -mod=vendor -o /hwlatdetect-runner hwlatdetect-runner/main.go

FROM registry.redhat.io/ubi9/ubi-minimal:9.5

RUN mkdir -p /usr/local/etc/cnf

COPY --from=oc /usr/bin/oc /usr/bin/oc
COPY --from=builder ${PKG_PATH}/cnf-tests/submodules/cluster-node-tuning-operator/build/_output/bin/latency-e2e.test /usr/bin/latency-e2e.test
COPY --from=builder ${PKG_PATH}/cnf-tests/entrypoint/test-run.sh /usr/bin/test-run.sh
COPY --from=builder ${PKG_PATH}/cnf-tests/bin/mirror /usr/bin/mirror
COPY --from=builder ${PKG_PATH}/cnf-tests/mirror/images.json /usr/local/etc/cnf
COPY --from=builder ${UTILS_PATH}/oslat-runner /usr/bin/oslat-runner
COPY --from=builder ${UTILS_PATH}/cyclictest-runner /usr/bin/cyclictest-runner
COPY --from=builder ${UTILS_PATH}/hwlatdetect-runner /usr/bin/hwlatdetect-runner
COPY --from=builder ${UTILS_PATH}/stresser/stresser /usr/bin/stresser
COPY --from=builder ${UTILS_PATH}/sctptester/sctptest /usr/bin/sctptest
COPY --from=builder ${UTILS_PATH}/sctptester/hugepages-allocator /usr/bin/hugepages-allocator

RUN sed -i 's/quay.io\/openshift-kni\//registry.redhat.io\/openshift4\//g' /usr/local/etc/cnf/images.json
RUN sed -i 's/cnf-tests:4.19/cnf-tests-rhel9:v4.19/g' /usr/local/etc/cnf/images.json
RUN sed -i 's/dpdk:4.19/dpdk-base-rhel8:v4.19/g' /usr/local/etc/cnf/images.json

ENV IMAGE_REGISTRY=registry.redhat.io/openshift4/
ENV CNF_TESTS_IMAGE=cnf-tests-rhel9:v4.19
ENV DPDK_TESTS_IMAGE=dpdk-base-rhel8:v4.19

CMD ["/usr/bin/test-run.sh"]
